CREATE DATABASE school;
USE school;

CREATE TABLE student(
studentID INT PRIMARY KEY,
FIRSTNAME VARCHAR(50),
LASTNAME VARCHAR(50),
EMAIL VARCHAR(100) UNIQUE
);
CREATE TABLE courses(
COURSEID INT PRIMARY KEY,
COURSENAME VARCHAR(100)
);
CREATE TABLE enrollments(
enrollmentID INT PRIMARY KEY AUTO_INCREMENT,
studentID INT,
COURSEID INT,
enrollmentDATE INT,
FOREIGN KEY (studentID) REFRENCES student(studentID),
FOREIGN KEY(COURSEID) REFRENCES courses(COURSEID)
);
DROP TABLE enrollment;
INSERT INTO student(studentID, FIRSTNAME, LASTNAME, EMAIL)
VALUES(432,'ALI','AHMAD','ALIdeo34@gmail.com');
INSERT INTO courses(COURSEID,COURSENAME)
VALUES(768,'DBMS');
INSERT INTO enrollments(studentID,COURSEID,enrollmentDATE)
VALUES(432,768,'3-4-2004'); 
SELECT * FROM student;
SELECT * FROM enrollments;
SELECT * FROM courses;